#!/usr/bin/env bash
# usuń migracje i bazę danych
rm app/migrations/000* accounts/migrations/000* db.sqlite3
python manage.py makemigrations dev
python manage.py migrate dev
# 0.0.0.0 vs 127.0.0.1 vs localhost?
# https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost
# python manage.py runserver localhost:8000 dev
python manage.py runserver 0.0.0.0:8000 dev
